from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional, TYPE_CHECKING
import json

if TYPE_CHECKING:
    from .lammps_input_writer import RelaxFFParams


@dataclass
class MDOutputs:
    in_relax_min:   str
    in_relax_heat:  str
    in_relax_equil: str
    run_sh:         str


# ══════════════════════════════════════════════════════════════════════════
# Part 1 — in.relax_min:  soft pushoff  →  CG minimize  →  write_dump
# Three-stage split: min → heat → equil  (one `run` per LAMMPS process)
# ══════════════════════════════════════════════════════════════════════════

def write_in_relax_min(
    path: Path,
    *,
    relax_ff:            "RelaxFFParams",
    data_file:           str   = "data.file",
    # ── Soft pushoff ─────────────────────────────────────────────────────
    soft_cutoff:         float = 2.0,      # Å
    soft_ramp_max:       float = 50.0,     # kcal/mol
    soft_steps:          int   = 2000,
    nve_limit:           float = 0.1,      # Å/step
    # ── CG minimize ──────────────────────────────────────────────────────
    min_etol:            float = 1.0e-4,
    min_ftol:            float = 1.0e-3,
    min_maxiter:         int   = 1000,
    min_maxeval:         int   = 5000,
    min_dmax:            float = 0.2,
    min_dump_every:      int   = 10,       # trajectory frames during minimize
    # ── Reflecting wall — confine solvent below vacuum ───────────────────
    z_wall:              Optional[float] = None,  # Å — wall position (z_el_hi + buffer)
    # ── QM (slab) atom ID range — freeze during relax ────────────────────
    qm_lo:               Optional[int] = None,
    qm_hi:               Optional[int] = None,
) -> None:
    """
    Part 1 of three-stage MM pre-equilibration.

    Split into a separate LAMMPS invocation to work around the macOS FFTW/PPPM
    segfault bug in LAMMPS 2025: any PPPM reinitialization (write_data,
    write_restart, or even the destructor) crashes with a segfault in
    fftw_plan_awake.

    data.file already includes vacuum in z (from config vacuum_z).

    Protocol
    --------
    Stage 0  pair_style soft + fix nve/limit   → relieve extreme packmol overlaps
    Stage 1  CG minimize with real force field  → refine to local minimum
    Output   write_dump (no init() call → no PPPM reinit → no crash)
    """
    ff = relax_ff

    # ── groups / freeze block ────────────────────────────────────────────
    if qm_lo is not None and qm_hi is not None:
        group_block_soft = (
            f"group           QM      id {qm_lo}:{qm_hi}\n"
            f"group           SOLVENT subtract all QM\n\n"
            f"velocity        QM set 0.0 0.0 0.0\n"
            f"fix             freezeQM QM setforce 0.0 0.0 0.0\n"
        )
        nve_group        = "SOLVENT"
        wall_group       = "SOLVENT"
        freeze_for_min   = f"fix             freezeQM QM setforce 0.0 0.0 0.0\n"
        unfix_soft_freeze = "unfix           freezeQM\n"
    else:
        group_block_soft  = "# (QM range unknown — moving all atoms)\n"
        nve_group         = "all"
        wall_group        = "all"
        freeze_for_min    = ""
        unfix_soft_freeze = ""

    # ── Harmonic wall — prevent solvent from drifting into vacuum ────────
    # wall/harmonic: epsilon=1.0 sigma=1.0 cutoff=5.0  (soft repulsion)
    if z_wall is not None:
        wall_fix = f"fix             WALL {wall_group} wall/harmonic zhi {z_wall:.4f} 1.0 1.0 5.0 units box\n"
        unfix_wall = "unfix           WALL\n"
    else:
        wall_fix   = ""
        unfix_wall = ""

    # ── pair_coeff / bond_coeff / angle_coeff lines ──────────────────────
    pc_block = "\n".join(ff.lj_pair_coeff_lines)
    bc_block = "\n".join(ff.bond_coeff_lines)
    ac_block = "\n".join(ff.angle_coeff_lines)

    # ── TIP4P charge override ────────────────────────────────────────────
    if ff.use_tip4p and ff.water_O_tid and ff.water_H_tid:
        charge_block = (
            f"set             type {ff.water_O_tid} charge {ff.o_charge:.5f}   # Ow (charge on M-site)\n"
            f"set             type {ff.water_H_tid} charge {ff.h_charge:.5f}   # Hw\n"
        )
    else:
        charge_block = ""

    txt = f"""\
# in.relax_min — Part 1: Soft pushoff + CG minimize
# Auto-generated by cesbuild  (md_workflow.py)
# Run FIRST, then in.relax_heat, then in.relax_equil  (via run_relax.sh)
#
# Split into three LAMMPS invocations (one `run` each) to avoid macOS
# FFTW/PPPM segfault on PPPM reinitialization (LAMMPS 2025 bug).
# ======================================================================

units           real
atom_style      full
boundary        p p f   # slab geometry: non-periodic z

pair_style      soft {soft_cutoff}
special_bonds   lj/coul 0.0 0.0 1.0
bond_style      harmonic
angle_style     harmonic
dihedral_style  none
improper_style  none

read_data       {data_file}
# NOTE: data.file box already includes vacuum_z above water and z_buffer_lo below slab
reset_timestep  0

{bc_block}
{ac_block}

pair_coeff      * *  0.0
variable        prefactor equal ramp(0,{soft_ramp_max:.0f})
fix             SOFT all adapt 1 pair soft a * * v_prefactor

{group_block_soft}
{wall_fix}fix             PUSH {nve_group} nve/limit {nve_limit}

thermo          200
thermo_style    custom step temp pe ke etotal press vol
run             {soft_steps}

unfix           PUSH
unfix           SOFT
{unfix_soft_freeze}
# ======================================================================
# Stage 1: CG minimize with real force field
# ======================================================================
{ff.pair_style_line}
{ff.kspace_line}
kspace_modify   slab 3.0   # required for p p f slab electrostatics

{pc_block}

{charge_block}
{freeze_for_min}
neighbor        2.0 bin
neigh_modify    delay 0 every 1 check yes

thermo          100
thermo_style    custom step temp pe ke etotal press vol

# dump every {min_dump_every} steps → full minimize trajectory for visualization
dump            MIN all custom {min_dump_every} min_traj.lammpstrj id type x y z
dump_modify     MIN sort id

min_style       cg
min_modify      dmax {min_dmax}
minimize        {min_etol} {min_ftol} {min_maxiter} {min_maxeval}

undump          MIN
{unfix_wall}
# Single final frame
# write_dump does NOT call init() → no PPPM reinit → no FFTW crash
reset_timestep  0
write_dump      all custom minimized.dump id type x y z modify sort id
"""
    path.write_text(txt, encoding="utf-8")


# ══════════════════════════════════════════════════════════════════════════
# Part 2 — in.relax_heat:  read_data + read_dump  →  NVT heating
# ══════════════════════════════════════════════════════════════════════════

def _nvt_common_header(
    ff: "RelaxFFParams",
    data_file: str,
    minimized_dump: str,
    qm_lo: Optional[int],
    qm_hi: Optional[int],
    z_wall: Optional[float],
) -> dict:
    """Build common text blocks for NVT scripts (heat & equil)."""

    # ── groups / freeze block ────────────────────────────────────────────
    if qm_lo is not None and qm_hi is not None:
        group_block = (
            f"group           QM      id {qm_lo}:{qm_hi}\n"
            f"group           SOLVENT subtract all QM\n\n"
            f"velocity        QM set 0.0 0.0 0.0\n"
            f"fix             freezeQM QM setforce 0.0 0.0 0.0\n"
        )
        vel_group    = "SOLVENT"
        nvt_group    = "SOLVENT"
        wall_group   = "SOLVENT"
        unfix_freeze = "unfix           freezeQM\n"
    else:
        group_block  = "# (QM range unknown — thermostating all atoms)\n"
        vel_group    = "all"
        nvt_group    = "all"
        wall_group   = "all"
        unfix_freeze = ""

    # ── Harmonic wall ────────────────────────────────────────────────────
    if z_wall is not None:
        wall_fix = f"fix             WALL {wall_group} wall/harmonic zhi {z_wall:.4f} 1.0 1.0 5.0 units box\n"
        unfix_wall = "unfix           WALL\n"
    else:
        wall_fix   = ""
        unfix_wall = ""

    # ── SHAKE block ──────────────────────────────────────────────────────
    if ff.water_bond_type and ff.water_angle_type:
        shake_fix = (
            f"fix             SHAKE {nvt_group} shake 1.0e-4 20 500"
            f" b {ff.water_bond_type} a {ff.water_angle_type}"
            f"   # keep water geometry rigid\n"
        )
        unfix_shake = "unfix           SHAKE\n"
    else:
        shake_fix   = "# (no SHAKE: bond/angle type not found)\n"
        unfix_shake = ""

    # ── TIP4P charge override ────────────────────────────────────────────
    if ff.use_tip4p and ff.water_O_tid and ff.water_H_tid:
        charge_block = (
            f"set             type {ff.water_O_tid} charge {ff.o_charge:.5f}   # Ow (charge on M-site)\n"
            f"set             type {ff.water_H_tid} charge {ff.h_charge:.5f}   # Hw\n"
        )
    else:
        charge_block = ""

    pc_block = "\n".join(ff.lj_pair_coeff_lines)
    bc_block = "\n".join(ff.bond_coeff_lines)
    ac_block = "\n".join(ff.angle_coeff_lines)

    return dict(
        group_block=group_block, vel_group=vel_group, nvt_group=nvt_group,
        wall_group=wall_group, unfix_freeze=unfix_freeze,
        wall_fix=wall_fix, unfix_wall=unfix_wall,
        shake_fix=shake_fix, unfix_shake=unfix_shake,
        charge_block=charge_block,
        pc_block=pc_block, bc_block=bc_block, ac_block=ac_block,
    )


def write_in_relax_heat(
    path: Path,
    *,
    relax_ff:            "RelaxFFParams",
    data_file:           str   = "data.file",
    minimized_dump:      str   = "minimized.dump",
    # ── Stage 2: Heat  t_start → t_target ────────────────────────────────
    t_start:             float = 10.0,
    t_target:            float = 300.0,
    tdamp_fs:            float = 100.0,
    heat_steps:          int   = 10000,
    # ── General MD ───────────────────────────────────────────────────────
    timestep_fs:         float = 1.0,
    dump_every:          int   = 2000,
    # ── Reflecting wall — confine solvent below vacuum ───────────────────
    z_wall:              Optional[float] = None,
    # ── QM (slab) atom ID range — freeze during relax ────────────────────
    qm_lo:               Optional[int] = None,
    qm_hi:               Optional[int] = None,
) -> None:
    """
    Part 2 of three-stage MM pre-equilibration: NVT heating.

    Starts a FRESH LAMMPS process (no PPPM state carried over from Part 1).
    Reads topology from data.file, overlays minimized coords from Part 1 dump.
    Outputs heated.dump via write_dump (avoids PPPM reinit crash).

    Protocol
    --------
    Stage 2  NVT heat t_start→t_target K  → gentle ramp
    Output   write_dump → heated.dump (no PPPM reinit)
    """
    ff = relax_ff
    heat_ps = heat_steps * timestep_fs / 1000.0
    c = _nvt_common_header(ff, data_file, minimized_dump, qm_lo, qm_hi, z_wall)

    txt = f"""\
# in.relax_heat — Part 2: NVT heating  {t_start:.0f} K → {t_target:.0f} K
# Auto-generated by cesbuild  (md_workflow.py)
# Run AFTER in.relax_min has produced {minimized_dump}
#
# Fresh LAMMPS process — no PPPM state from Part 1.
# Only ONE run command per LAMMPS invocation to avoid macOS FFTW/PPPM
# segfault on PPPM reinitialization (LAMMPS 2025 bug).
# ======================================================================

units           real
atom_style      full
boundary        p p f   # slab geometry: non-periodic z

special_bonds   lj/coul 0.0 0.0 1.0
bond_style      harmonic
angle_style     harmonic
dihedral_style  none
improper_style  none

{ff.pair_style_line}
{ff.kspace_line}
kspace_modify   slab 3.0   # required for p p f slab electrostatics

read_data       {data_file}
# NOTE: data.file box already includes vacuum_z above water and z_buffer_lo below slab
reset_timestep  0

{c['pc_block']}

{c['bc_block']}
{c['ac_block']}

{c['charge_block']}
# Load minimized coordinates (overwrites packmol positions from data.file)
read_dump       {minimized_dump} 0 x y z box no

{c['group_block']}
{c['wall_fix']}neighbor        2.0 bin
neigh_modify    delay 0 every 1 check yes

# ======================================================================
# Stage 2: Gradual heating  {t_start:.0f} K → {t_target:.0f} K  ({heat_ps:.1f} ps)
#          Slow ramp prevents explosive dynamics from packmol geometry
# ======================================================================
timestep        {timestep_fs}
{c['shake_fix']}
velocity        {c['vel_group']} create {t_start:.1f} 12345 mom yes rot yes dist gaussian

thermo          500
thermo_style    custom step temp pe ke etotal press vol
dump            D1 all custom {dump_every} heat.lammpstrj id type q x y z
dump_modify     D1 sort id

fix             NVT1 {c['nvt_group']} nvt temp {t_start:.1f} {t_target:.1f} {tdamp_fs:.1f}
run             {heat_steps}
unfix           NVT1

{c['unfix_shake']}{c['unfix_wall']}{c['unfix_freeze']}undump          D1
# write_dump does NOT call init() → no PPPM reinit → no FFTW crash
reset_timestep  0
write_dump      all custom heated.dump id type x y z vx vy vz modify sort id
"""
    path.write_text(txt, encoding="utf-8")


# ══════════════════════════════════════════════════════════════════════════
# Part 3 — in.relax_equil:  read_data + read_dump → NVT equilibration
# ══════════════════════════════════════════════════════════════════════════

def write_in_relax_equil(
    path: Path,
    *,
    relax_ff:            "RelaxFFParams",
    data_file:           str   = "data.file",
    heated_dump:         str   = "heated.dump",
    # ── Stage 3: NVT equilibration at t_target ───────────────────────────
    t_target:            float = 300.0,
    tdamp_fs:            float = 100.0,
    equil_steps:         int   = 30000,
    # ── General MD ───────────────────────────────────────────────────────
    timestep_fs:         float = 1.0,
    dump_every:          int   = 2000,
    write_equilibrated:  str   = "equilibrated.data",
    # ── Reflecting wall — confine solvent below vacuum ───────────────────
    z_wall:              Optional[float] = None,
    # ── QM (slab) atom ID range — freeze during relax ────────────────────
    qm_lo:               Optional[int] = None,
    qm_hi:               Optional[int] = None,
) -> None:
    """
    Part 3 of three-stage MM pre-equilibration: NVT equilibration.

    Starts a FRESH LAMMPS process (no PPPM state from Part 2).
    Reads topology from data.file, overlays heated coords+velocities from
    heated.dump produced by Part 2.

    Protocol
    --------
    Stage 3  NVT t_target K  → equilibrate structure before CES2
    Output   write_dump → equilibrated.dump (safe, no PPPM reinit)
             Also writes equilibrated.data via write_data (may crash on macOS,
             but it's the last command so data is not needed for next stage)
    """
    ff = relax_ff
    equil_ps = equil_steps * timestep_fs / 1000.0
    c = _nvt_common_header(ff, data_file, heated_dump, qm_lo, qm_hi, z_wall)

    txt = f"""\
# in.relax_equil — Part 3: NVT equilibration at {t_target:.0f} K
# Auto-generated by cesbuild  (md_workflow.py)
# Run AFTER in.relax_heat has produced {heated_dump}
#
# Fresh LAMMPS process — no PPPM state from Part 2.
# Only ONE run command per LAMMPS invocation to avoid macOS FFTW/PPPM
# segfault on PPPM reinitialization (LAMMPS 2025 bug).
# ======================================================================

units           real
atom_style      full
boundary        p p f   # slab geometry: non-periodic z

special_bonds   lj/coul 0.0 0.0 1.0
bond_style      harmonic
angle_style     harmonic
dihedral_style  none
improper_style  none

{ff.pair_style_line}
{ff.kspace_line}
kspace_modify   slab 3.0   # required for p p f slab electrostatics

read_data       {data_file}
# NOTE: data.file box already includes vacuum_z above water and z_buffer_lo below slab
reset_timestep  0

{c['pc_block']}

{c['bc_block']}
{c['ac_block']}

{c['charge_block']}
# Load heated coordinates + velocities from Stage 2
read_dump       {heated_dump} 0 x y z vx vy vz box no

{c['group_block']}
{c['wall_fix']}neighbor        2.0 bin
neigh_modify    delay 0 every 1 check yes

# ======================================================================
# Stage 3: NVT equilibration at {t_target:.0f} K  ({equil_ps:.1f} ps)
# ======================================================================
timestep        {timestep_fs}
{c['shake_fix']}
thermo          500
thermo_style    custom step temp pe ke etotal press vol
dump            D1 all custom {dump_every} equil.lammpstrj id type q x y z
dump_modify     D1 sort id

fix             NVT2 {c['nvt_group']} nvt temp {t_target:.1f} {t_target:.1f} {tdamp_fs:.1f}
run             {equil_steps}
unfix           NVT2

{c['unfix_shake']}{c['unfix_wall']}{c['unfix_freeze']}undump          D1
# write_dump: safe (no PPPM reinit)
write_dump      all custom equilibrated.dump id type x y z vx vy vz modify sort id
# write_data: may crash on macOS (PPPM reinit in destructor), but run is already done
write_data      {write_equilibrated}
"""
    path.write_text(txt, encoding="utf-8")


# ══════════════════════════════════════════════════════════════════════════
# Submit / wrapper scripts
# ══════════════════════════════════════════════════════════════════════════

def write_run_sh(path: Path, lmp_cmd: str = "lmp_mpi") -> None:
    """Wrapper script that runs all three LAMMPS invocations sequentially."""
    path.write_text(f"""#!/bin/bash
# run_relax.sh — three-stage MM pre-equilibration
# Usage: bash run_relax.sh [lmp_command]
# Auto-generated by cesbuild  (md_workflow.py)
#
# Each stage runs in a SEPARATE LAMMPS process to avoid the macOS
# FFTW/PPPM segfault bug (PPPM reinitialization on every `run` command).
# NOTE: We do NOT use `set -e` because LAMMPS may segfault in its
# destructor (PPPM cleanup) even after all computations succeed.
# Instead we check that the expected output file was created.

LMP=${{1:-{lmp_cmd}}}

echo "==== Part 1: Soft pushoff + CG minimize ===="
echo "     ($LMP -in in.relax_min)"
$LMP -in in.relax_min || true   # destructor may segfault — that's OK
if [ ! -f minimized.dump ]; then
    echo "ERROR: Part 1 failed — minimized.dump not found."
    exit 1
fi
echo "     -> minimized.dump OK"
echo ""

echo "==== Part 2: NVT heating ===="
echo "     ($LMP -in in.relax_heat)"
$LMP -in in.relax_heat || true
if [ ! -f heated.dump ]; then
    echo "ERROR: Part 2 failed — heated.dump not found."
    exit 1
fi
echo "     -> heated.dump OK"
echo ""

echo "==== Part 3: NVT equilibration ===="
echo "     ($LMP -in in.relax_equil)"
$LMP -in in.relax_equil || true
if [ ! -f equilibrated.dump ]; then
    echo "ERROR: Part 3 failed — equilibrated.dump not found."
    exit 1
fi
echo "     -> equilibrated.dump OK"
echo ""

echo "==== Done! Output: equilibrated.data / equilibrated.dump ===="
""", encoding="utf-8")


# ══════════════════════════════════════════════════════════════════════════
# Bundle generator  (called by cesbuild main)
# ══════════════════════════════════════════════════════════════════════════

def generate_md_bundle(
    export_dir:  Path,
    md_cfg:      Dict,
    relax_ff:    "Optional[RelaxFFParams]" = None,
) -> MDOutputs:
    """
    Generate the MD pre-relax bundle:
      in.relax_min, in.relax_heat, in.relax_equil, run_relax.sh, submit scripts.

    Three-stage approach (each a separate LAMMPS process with ONE run command):
      Part 1 (in.relax_min):   soft pushoff → CG minimize → write_dump
      Part 2 (in.relax_heat):  read_data + read_dump → NVT heat → write_dump
      Part 3 (in.relax_equil): read_data + read_dump → NVT equil → write_data
    Separate LAMMPS invocations avoid the macOS FFTW/PPPM segfault bug
    (PPPM reinitialization on every `run` command).
    """
    # ── QM atom ID range and z_wall from build_summary.json ──────────────
    qm_lo: Optional[int]   = None
    qm_hi: Optional[int]   = None
    z_wall: Optional[float] = None
    wall_buffer: float = float(md_cfg.get("wall_buffer", 10.0))  # Å above z_el_hi
    summary_path = export_dir / "build_summary.json"
    if summary_path.exists():
        try:
            summary = json.loads(summary_path.read_text(encoding="utf-8"))
            n_mm = int(summary.get("n_mm", 0))
            n_qm = int(summary.get("n_qm", 0))
            if n_mm > 0 and n_qm > 0:
                qm_lo = n_mm + 1
                qm_hi = n_mm + n_qm
            # Reflecting wall at top of electrolyte + buffer
            box_info = summary.get("box", {})
            z_el_hi = box_info.get("z_el_hi")
            if z_el_hi is not None:
                z_wall = float(z_el_hi) + wall_buffer
        except Exception:
            pass

    # ── Common kwargs for NVT stages ─────────────────────────────────────
    common_nvt_kw = dict(
        z_wall=z_wall,
        qm_lo=qm_lo,
        qm_hi=qm_hi,
    )

    # ── in.relax_min + in.relax_heat + in.relax_equil ────────────────────
    if relax_ff is not None:
        data_file = md_cfg.get("data_file", "data.file")

        write_in_relax_min(
            export_dir / "in.relax_min",
            relax_ff=relax_ff,
            data_file=data_file,
            soft_cutoff=float(md_cfg.get("soft_cutoff",    2.0)),
            soft_ramp_max=float(md_cfg.get("soft_ramp_max", 50.0)),
            soft_steps=int(md_cfg.get("soft_steps",        2000)),
            nve_limit=float(md_cfg.get("nve_limit",        0.1)),
            min_etol=float(md_cfg.get("min_etol",          1.0e-4)),
            min_ftol=float(md_cfg.get("min_ftol",          1.0e-3)),
            min_maxiter=int(md_cfg.get("min_maxiter",      1000)),
            min_maxeval=int(md_cfg.get("min_maxeval",      5000)),
            min_dmax=float(md_cfg.get("min_dmax",          0.2)),
            min_dump_every=int(md_cfg.get("min_dump_every", 10)),
            z_wall=z_wall,
            qm_lo=qm_lo,
            qm_hi=qm_hi,
        )

        write_in_relax_heat(
            export_dir / "in.relax_heat",
            relax_ff=relax_ff,
            data_file=data_file,
            minimized_dump=md_cfg.get("minimized_dump", "minimized.dump"),
            t_start=float(md_cfg.get("t_start",        10.0)),
            t_target=float(md_cfg.get("t_target",      300.0)),
            tdamp_fs=float(md_cfg.get("tdamp_fs",      100.0)),
            heat_steps=int(md_cfg.get("heat_steps",   10000)),
            timestep_fs=float(md_cfg.get("timestep_fs",  1.0)),
            dump_every=int(md_cfg.get("dump_every",    2000)),
            **common_nvt_kw,
        )

        write_in_relax_equil(
            export_dir / "in.relax_equil",
            relax_ff=relax_ff,
            data_file=data_file,
            heated_dump=md_cfg.get("heated_dump", "heated.dump"),
            t_target=float(md_cfg.get("t_target",      300.0)),
            tdamp_fs=float(md_cfg.get("tdamp_fs",      100.0)),
            equil_steps=int(md_cfg.get("equil_steps", 30000)),
            timestep_fs=float(md_cfg.get("timestep_fs",  1.0)),
            dump_every=int(md_cfg.get("dump_every",    2000)),
            write_equilibrated=md_cfg.get("write_equilibrated", "equilibrated.data"),
            **common_nvt_kw,
        )
    else:
        for fname in ("in.relax_min", "in.relax_heat", "in.relax_equil"):
            (export_dir / fname).write_text(
                f"# WARNING: relax_ff not provided — FF parameters missing.\n"
                f"# Re-run cesbuild with md_relax.enabled: true to regenerate.\n",
                encoding="utf-8",
            )

    # ── run_relax.sh ─────────────────────────────────────────────────────
    write_run_sh(export_dir / "run_relax.sh")
    try:
        (export_dir / "run_relax.sh").chmod(0o755)
    except Exception:
        pass

    # ── view_dump.py utility ─────────────────────────────────────────────
    _copy_view_dump(export_dir)

    return MDOutputs(
        in_relax_min="export/in.relax_min",
        in_relax_heat="export/in.relax_heat",
        in_relax_equil="export/in.relax_equil",
        run_sh="export/run_relax.sh",
    )


def _copy_view_dump(export_dir: Path) -> None:
    """Copy view_dump.py into the export directory if it exists in the package."""
    src = Path(__file__).parent.parent / "export" / "view_dump.py"
    dst = export_dir / "view_dump.py"
    if src.exists() and not dst.exists():
        try:
            dst.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
        except Exception:
            pass
