from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional, TYPE_CHECKING
import json

if TYPE_CHECKING:
    from .lammps_input_writer import RelaxFFParams


@dataclass
class MDOutputs:
    in_relax_min: str
    in_relax_nvt: str
    sbatch:       str
    pbs:          str
    run_sh:       str


# ══════════════════════════════════════════════════════════════════════════
# Part 1 — in.relax_min:  soft pushoff  →  CG minimize  →  write_dump
# ══════════════════════════════════════════════════════════════════════════

def write_in_relax_min(
    path: Path,
    *,
    relax_ff:            "RelaxFFParams",
    data_file:           str   = "data.file",
    # ── Soft pushoff ─────────────────────────────────────────────────────
    soft_cutoff:         float = 2.0,      # Å
    soft_ramp_max:       float = 50.0,     # kcal/mol
    soft_steps:          int   = 2000,
    nve_limit:           float = 0.1,      # Å/step
    # ── CG minimize ──────────────────────────────────────────────────────
    min_etol:            float = 1.0e-4,
    min_ftol:            float = 1.0e-3,
    min_maxiter:         int   = 1000,
    min_maxeval:         int   = 5000,
    min_dmax:            float = 0.2,
    min_dump_every:      int   = 10,       # trajectory frames during minimize
    # ── QM (slab) atom ID range — freeze during relax ────────────────────
    qm_lo:               Optional[int] = None,
    qm_hi:               Optional[int] = None,
) -> None:
    """
    Part 1 of two-stage MM pre-equilibration.

    Split into a separate LAMMPS invocation to work around the macOS FFTW/PPPM
    segfault bug in LAMMPS 2025: any PPPM reinitialization (write_data,
    write_restart, or even the destructor) crashes with a segfault in
    fftw_plan_awake.

    Protocol
    --------
    Stage 0  pair_style soft + fix nve/limit   → relieve extreme packmol overlaps
    Stage 1  CG minimize with real force field  → refine to local minimum
    Output   write_dump (no init() call → no PPPM reinit → no crash)
    """
    ff = relax_ff

    # ── groups / freeze block ────────────────────────────────────────────
    if qm_lo is not None and qm_hi is not None:
        group_block_soft = (
            f"group           QM      id {qm_lo}:{qm_hi}\n"
            f"group           SOLVENT subtract all QM\n\n"
            f"velocity        QM set 0.0 0.0 0.0\n"
            f"fix             freezeQM QM setforce 0.0 0.0 0.0\n"
        )
        nve_group        = "SOLVENT"
        freeze_for_min   = f"fix             freezeQM QM setforce 0.0 0.0 0.0\n"
        unfix_soft_freeze = "unfix           freezeQM\n"
    else:
        group_block_soft  = "# (QM range unknown — moving all atoms)\n"
        nve_group         = "all"
        freeze_for_min    = ""
        unfix_soft_freeze = ""

    # ── pair_coeff / bond_coeff / angle_coeff lines ──────────────────────
    pc_block = "\n".join(ff.lj_pair_coeff_lines)
    bc_block = "\n".join(ff.bond_coeff_lines)
    ac_block = "\n".join(ff.angle_coeff_lines)

    # ── TIP4P charge override ────────────────────────────────────────────
    if ff.use_tip4p and ff.water_O_tid and ff.water_H_tid:
        charge_block = (
            f"set             type {ff.water_O_tid} charge {ff.o_charge:.5f}   # Ow (charge on M-site)\n"
            f"set             type {ff.water_H_tid} charge {ff.h_charge:.5f}   # Hw\n"
        )
    else:
        charge_block = ""

    txt = f"""\
# in.relax_min — Part 1: Soft pushoff + CG minimize
# Auto-generated by cesbuild  (md_workflow.py)
# Run FIRST, then run in.relax_nvt  (via run_relax.sh)
#
# Split into two LAMMPS invocations to avoid macOS FFTW/PPPM segfault
# on PPPM reinitialization (LAMMPS 2025 bug).
# ======================================================================

units           real
atom_style      full
boundary        p p f   # slab geometry: non-periodic z

pair_style      soft {soft_cutoff}
special_bonds   lj/coul 0.0 0.0 1.0
bond_style      harmonic
angle_style     harmonic
dihedral_style  none
improper_style  none

read_data       {data_file}
reset_timestep  0

{bc_block}
{ac_block}

pair_coeff      * *  0.0
variable        prefactor equal ramp(0,{soft_ramp_max:.0f})
fix             SOFT all adapt 1 pair soft a * * v_prefactor

{group_block_soft}
fix             PUSH {nve_group} nve/limit {nve_limit}

thermo          200
thermo_style    custom step temp pe ke etotal press vol
run             {soft_steps}

unfix           PUSH
unfix           SOFT
{unfix_soft_freeze}
# ======================================================================
# Stage 1: CG minimize with real force field
# ======================================================================
{ff.pair_style_line}
{ff.kspace_line}
kspace_modify   slab 3.0   # required for p p f slab electrostatics

{pc_block}

{charge_block}
{freeze_for_min}
neighbor        2.0 bin
neigh_modify    delay 0 every 1 check yes

thermo          100
thermo_style    custom step temp pe ke etotal press vol

# dump every {min_dump_every} steps → full minimize trajectory for visualization
dump            MIN all custom {min_dump_every} min_traj.lammpstrj id type x y z
dump_modify     MIN sort id

min_style       cg
min_modify      dmax {min_dmax}
minimize        {min_etol} {min_ftol} {min_maxiter} {min_maxeval}

undump          MIN

# Single final frame
# write_dump does NOT call init() → no PPPM reinit → no FFTW crash
reset_timestep  0
write_dump      all custom minimized.dump id type x y z modify sort id
"""
    path.write_text(txt, encoding="utf-8")


# ══════════════════════════════════════════════════════════════════════════
# Part 2 — in.relax_nvt:  read_data + read_dump  →  NVT heat + equil
# ══════════════════════════════════════════════════════════════════════════

def write_in_relax_nvt(
    path: Path,
    *,
    relax_ff:            "RelaxFFParams",
    data_file:           str   = "data.file",
    minimized_dump:      str   = "minimized.dump",
    # ── Stage 2: Heat  t_start → t_target ────────────────────────────────
    t_start:             float = 10.0,
    t_target:            float = 300.0,
    tdamp_fs:            float = 100.0,
    heat_steps:          int   = 10000,
    # ── Stage 3: NVT equilibration at t_target ───────────────────────────
    equil_steps:         int   = 30000,
    # ── General MD ───────────────────────────────────────────────────────
    timestep_fs:         float = 1.0,
    dump_every:          int   = 2000,
    write_equilibrated:  str   = "equilibrated.data",
    # ── QM (slab) atom ID range — freeze during relax ────────────────────
    qm_lo:               Optional[int] = None,
    qm_hi:               Optional[int] = None,
) -> None:
    """
    Part 2 of two-stage MM pre-equilibration.

    Starts a FRESH LAMMPS process (no PPPM state carried over from Part 1).
    Reads topology from data.file, then overlays minimized coordinates from
    the dump produced by Part 1.

    Protocol
    --------
    Stage 2  NVT heat t_start→t_target K   → gentle ramp
    Stage 3  NVT t_target K                 → equilibrate structure before CES2
    """
    ff = relax_ff

    heat_ps  = heat_steps  * timestep_fs / 1000.0
    equil_ps = equil_steps * timestep_fs / 1000.0

    # ── groups / freeze block ────────────────────────────────────────────
    if qm_lo is not None and qm_hi is not None:
        group_block = (
            f"group           QM      id {qm_lo}:{qm_hi}\n"
            f"group           SOLVENT subtract all QM\n\n"
            f"velocity        QM set 0.0 0.0 0.0\n"
            f"fix             freezeQM QM setforce 0.0 0.0 0.0\n"
        )
        vel_group    = "SOLVENT"
        nvt_group    = "SOLVENT"
        unfix_freeze = "unfix           freezeQM\n"
    else:
        group_block  = "# (QM range unknown — thermostating all atoms)\n"
        vel_group    = "all"
        nvt_group    = "all"
        unfix_freeze = ""

    # ── SHAKE block ──────────────────────────────────────────────────────
    if ff.water_bond_type and ff.water_angle_type:
        shake_fix = (
            f"fix             SHAKE {nvt_group} shake 1.0e-4 20 500"
            f" b {ff.water_bond_type} a {ff.water_angle_type}"
            f"   # keep water geometry rigid\n"
        )
        unfix_shake = "unfix           SHAKE\n"
    else:
        shake_fix   = "# (no SHAKE: bond/angle type not found)\n"
        unfix_shake = ""

    # ── TIP4P charge override ────────────────────────────────────────────
    if ff.use_tip4p and ff.water_O_tid and ff.water_H_tid:
        charge_block = (
            f"set             type {ff.water_O_tid} charge {ff.o_charge:.5f}   # Ow (charge on M-site)\n"
            f"set             type {ff.water_H_tid} charge {ff.h_charge:.5f}   # Hw\n"
        )
    else:
        charge_block = ""

    # ── FF blocks ────────────────────────────────────────────────────────
    pc_block = "\n".join(ff.lj_pair_coeff_lines)
    bc_block = "\n".join(ff.bond_coeff_lines)
    ac_block = "\n".join(ff.angle_coeff_lines)

    txt = f"""\
# in.relax_nvt — Part 2: NVT heating + equilibration
# Auto-generated by cesbuild  (md_workflow.py)
# Run AFTER in.relax_min has produced {minimized_dump}
#
# Fresh LAMMPS process — no PPPM state from Part 1.
# ======================================================================

units           real
atom_style      full
boundary        p p f   # slab geometry: non-periodic z

special_bonds   lj/coul 0.0 0.0 1.0
bond_style      harmonic
angle_style     harmonic
dihedral_style  none
improper_style  none

{ff.pair_style_line}
{ff.kspace_line}
kspace_modify   slab 3.0   # required for p p f slab electrostatics

read_data       {data_file}
reset_timestep  0

{pc_block}

{bc_block}
{ac_block}

{charge_block}
# Load minimized coordinates (overwrites packmol positions from data.file)
read_dump       {minimized_dump} 0 x y z box no

{group_block}
neighbor        2.0 bin
neigh_modify    delay 0 every 1 check yes

# ======================================================================
# Stage 2: Gradual heating  {t_start:.0f} K → {t_target:.0f} K  ({heat_ps:.1f} ps)
#          Slow ramp prevents explosive dynamics from packmol geometry
# ======================================================================
timestep        {timestep_fs}
{shake_fix}
velocity        {vel_group} create {t_start:.1f} 12345 mom yes rot yes dist gaussian

thermo          500
thermo_style    custom step temp pe ke etotal press vol
dump            D1 all custom {dump_every} relax.lammpstrj id type q x y z
dump_modify     D1 sort id

fix             NVT1 {nvt_group} nvt temp {t_start:.1f} {t_target:.1f} {tdamp_fs:.1f}
run             {heat_steps}
unfix           NVT1

# ======================================================================
# Stage 3: NVT equilibration at {t_target:.0f} K  ({equil_ps:.1f} ps)
# ======================================================================
fix             NVT2 {nvt_group} nvt temp {t_target:.1f} {t_target:.1f} {tdamp_fs:.1f}
run             {equil_steps}
unfix           NVT2

{unfix_shake}{unfix_freeze}undump          D1
write_data      {write_equilibrated}
"""
    path.write_text(txt, encoding="utf-8")


# ══════════════════════════════════════════════════════════════════════════
# Submit / wrapper scripts
# ══════════════════════════════════════════════════════════════════════════

def write_sbatch(path: Path,
                job_name:     str   = "ces2_md_relax",
                partition:    str   = "compute",
                nodes:        int   = 1,
                ntasks:       int   = 32,
                time_hhmmss:  str   = "08:00:00",
                lmp_cmd:      str   = "lmp_mpi",
                out:          str   = "md.out",
                err:          str   = "md.err",
                module_lines: str   = "module load lammps\n") -> None:
    path.write_text(f"""#!/bin/bash
#SBATCH -J {job_name}
#SBATCH -p {partition}
#SBATCH -N {nodes}
#SBATCH -n {ntasks}
#SBATCH -t {time_hhmmss}
#SBATCH -o {out}
#SBATCH -e {err}

set -euo pipefail

{module_lines}
bash run_relax.sh {lmp_cmd}
""", encoding="utf-8")


def write_pbs(path: Path,
             job_name:     str = "ces2_md_relax",
             nodes:        int = 1,
             ppn:          int = 32,
             walltime:     str = "08:00:00",
             lmp_cmd:      str = "lmp_mpi",
             module_lines: str = "module load lammps\n") -> None:
    path.write_text(f"""#!/bin/bash
#PBS -N {job_name}
#PBS -l nodes={nodes}:ppn={ppn}
#PBS -l walltime={walltime}
#PBS -j oe

set -euo pipefail
cd $PBS_O_WORKDIR

{module_lines}
bash run_relax.sh {lmp_cmd}
""", encoding="utf-8")


def write_run_sh(path: Path, lmp_cmd: str = "lmp_mpi") -> None:
    """Wrapper script that runs both LAMMPS invocations sequentially."""
    path.write_text(f"""#!/bin/bash
# run_relax.sh — two-stage MM pre-equilibration
# Usage: bash run_relax.sh [lmp_command]
# Auto-generated by cesbuild  (md_workflow.py)
set -e

LMP=${{1:-{lmp_cmd}}}

echo "==== Part 1: Soft pushoff + CG minimize ===="
echo "     ($LMP -in in.relax_min)"
$LMP -in in.relax_min
echo ""

echo "==== Part 2: NVT heating + equilibration ===="
echo "     ($LMP -in in.relax_nvt)"
$LMP -in in.relax_nvt
echo ""

echo "==== Done! Output: equilibrated.data ===="
""", encoding="utf-8")


# ══════════════════════════════════════════════════════════════════════════
# Bundle generator  (called by cesbuild main)
# ══════════════════════════════════════════════════════════════════════════

def generate_md_bundle(
    export_dir:  Path,
    md_cfg:      Dict,
    relax_ff:    "Optional[RelaxFFParams]" = None,
) -> MDOutputs:
    """
    Generate the MD pre-relax bundle:
      in.relax_min, in.relax_nvt, run_relax.sh, submit scripts, view_dump.py.

    Two-stage approach:
      Part 1 (in.relax_min): soft pushoff → CG minimize → write_dump
      Part 2 (in.relax_nvt): read_data + read_dump → NVT heat + equil
    Separate LAMMPS invocations avoid the macOS FFTW/PPPM segfault bug.
    """
    # ── QM atom ID range from build_summary.json ─────────────────────────
    qm_lo: Optional[int] = None
    qm_hi: Optional[int] = None
    summary_path = export_dir / "build_summary.json"
    if summary_path.exists():
        try:
            summary = json.loads(summary_path.read_text(encoding="utf-8"))
            n_mm = int(summary.get("n_mm", 0))
            n_qm = int(summary.get("n_qm", 0))
            if n_mm > 0 and n_qm > 0:
                qm_lo = n_mm + 1
                qm_hi = n_mm + n_qm
        except Exception:
            pass

    # ── in.relax_min + in.relax_nvt ──────────────────────────────────────
    if relax_ff is not None:
        data_file = md_cfg.get("data_file", "data.file")

        write_in_relax_min(
            export_dir / "in.relax_min",
            relax_ff=relax_ff,
            data_file=data_file,
            soft_cutoff=float(md_cfg.get("soft_cutoff",    2.0)),
            soft_ramp_max=float(md_cfg.get("soft_ramp_max", 50.0)),
            soft_steps=int(md_cfg.get("soft_steps",        2000)),
            nve_limit=float(md_cfg.get("nve_limit",        0.1)),
            min_etol=float(md_cfg.get("min_etol",          1.0e-4)),
            min_ftol=float(md_cfg.get("min_ftol",          1.0e-3)),
            min_maxiter=int(md_cfg.get("min_maxiter",      1000)),
            min_maxeval=int(md_cfg.get("min_maxeval",      5000)),
            min_dmax=float(md_cfg.get("min_dmax",          0.2)),
            min_dump_every=int(md_cfg.get("min_dump_every", 10)),
            qm_lo=qm_lo,
            qm_hi=qm_hi,
        )

        write_in_relax_nvt(
            export_dir / "in.relax_nvt",
            relax_ff=relax_ff,
            data_file=data_file,
            minimized_dump=md_cfg.get("minimized_dump", "minimized.dump"),
            t_start=float(md_cfg.get("t_start",        10.0)),
            t_target=float(md_cfg.get("t_target",      300.0)),
            tdamp_fs=float(md_cfg.get("tdamp_fs",      100.0)),
            heat_steps=int(md_cfg.get("heat_steps",   10000)),
            equil_steps=int(md_cfg.get("equil_steps", 30000)),
            timestep_fs=float(md_cfg.get("timestep_fs",  1.0)),
            dump_every=int(md_cfg.get("dump_every",    2000)),
            write_equilibrated=md_cfg.get("write_equilibrated", "equilibrated.data"),
            qm_lo=qm_lo,
            qm_hi=qm_hi,
        )
    else:
        for fname in ("in.relax_min", "in.relax_nvt"):
            (export_dir / fname).write_text(
                f"# WARNING: relax_ff not provided — FF parameters missing.\n"
                f"# Re-run cesbuild with md_relax.enabled: true to regenerate.\n",
                encoding="utf-8",
            )

    # ── Submit scripts (now call run_relax.sh instead of in.relax) ───────
    sl = md_cfg.get("slurm", {})
    lmp_cmd_sl = sl.get("lmp_cmd", "lmp_mpi")
    write_sbatch(
        export_dir / "submit_md.sbatch",
        job_name=sl.get("job_name",     "ces2_md_relax"),
        partition=sl.get("partition",   "compute"),
        nodes=int(sl.get("nodes",       1)),
        ntasks=int(sl.get("ntasks",     32)),
        time_hhmmss=sl.get("time",      "08:00:00"),
        lmp_cmd=lmp_cmd_sl,
        out=sl.get("stdout",            "md.out"),
        err=sl.get("stderr",            "md.err"),
        module_lines=sl.get("module_lines", "module load lammps\n"),
    )

    pb = md_cfg.get("pbs", {})
    lmp_cmd_pb = pb.get("lmp_cmd", "lmp_mpi")
    write_pbs(
        export_dir / "submit_md.pbs",
        job_name=pb.get("job_name",   "ces2_md_relax"),
        nodes=int(pb.get("nodes",     1)),
        ppn=int(pb.get("ppn",         32)),
        walltime=pb.get("walltime",   "08:00:00"),
        lmp_cmd=lmp_cmd_pb,
        module_lines=pb.get("module_lines", "module load lammps\n"),
    )

    # ── run_relax.sh ─────────────────────────────────────────────────────
    write_run_sh(export_dir / "run_relax.sh")
    try:
        (export_dir / "run_relax.sh").chmod(0o755)
    except Exception:
        pass

    # ── view_dump.py utility ─────────────────────────────────────────────
    _copy_view_dump(export_dir)

    return MDOutputs(
        in_relax_min="export/in.relax_min",
        in_relax_nvt="export/in.relax_nvt",
        sbatch="export/submit_md.sbatch",
        pbs="export/submit_md.pbs",
        run_sh="export/run_relax.sh",
    )


def _copy_view_dump(export_dir: Path) -> None:
    """Copy view_dump.py into the export directory if it exists in the package."""
    src = Path(__file__).parent.parent / "export" / "view_dump.py"
    dst = export_dir / "view_dump.py"
    if src.exists() and not dst.exists():
        try:
            dst.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
        except Exception:
            pass
